#-------------------------------
# General Site Settings

title: Simons project space
logo:
author: Simon Sikkeland
description: Testing testing
email: example@gmail.com
phone: +47 123 45 678
address: Oslo, Norway
copyright: Copyright &copy; 2020 Designed by [Themefisher](https://themefisher.com) & Developed by [Getjekyllthemes](https://getjekyllthemes.com)

menu:
- {name: My projects, link: '/blog/projects'}
- {name: About, link: '/blog/about'}
# - {name: Portfolio, link: '/portfolio'}
- {name: Contact, link: '/blog/contact'}


#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

google-analytics: # UA-XXXXXX-X


#-------------------------------
# Comment Section (Disqus)

disqus-identifier: # Add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Hero Section

hero:
  hero-title: Learning by doing

social:
# - {icon: "ti-linkedin", link: "#"}
# - {icon: "ti-instagram", link: "#"}
# - {icon: "ti-dribbble", link: "#"}
# - {icon: "ti-twitter", link: "#"}


#-------------------------------
# About (Section and Page)

# About Section
blurb:


blurb-btn-link: '/about'
blurb-btn-name: know more


# About Page

# # Work Process Section
# work-process:
#   - title : "Research and Plan"
#     icon : "assets/images/icons/plan.png"
#     content : "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."

#   - title : "Design and Develop"
#     icon : "assets/images/icons/design.png"
#     content : "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."

#   - title : "Deliver"
#     icon : "assets/images/icons/print.png"
#     content : "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."


# # My Team Section
# team:
#   - title : "Jack Schenziwe"
#     image : "assets/images/team/johan-1.JPG"
#     designation : "Project Manager"

#   - title : "Julias Carlie"
#     image : "assets/images/team/robot.JPG"
#     designation : "Web Developer"

#   - title : "John Doe"
#     image : "assets/images/team/johan-2.JPG"
#     designation : "Designer"


#-------------------------------
# Skills Section

# skills-title: Skills
# skills:
# - {name: Machine Learning, color: '#fdb157', value: '90%'}
# - {name: Webdesign, color: '#9473e6', value: '99%'}
# - {name: Other shit, color: '#bdecf6', value: '80%'}
# - {name: Web App, color: '#ffbcaa', value: '69%'}
# - {name: life, color: '#999', value: '17%'}


#-------------------------------
# Services Section

services-title: Tinkering with
services:
- {
    name: Jekyll and JavaScript,
    icon: ti-world,
    description: 'Map the landscape from above, forrest, fields, urban areas and so on.',
    active: # Add true to select section
  }
- {
    name: Python,
    icon: ti-rocket,
    description: 'Map areas with risk of landslide, see hazzardeus areas in your municipality.',
    active: true # Add true to select section
  }
- {
    name: TensorFlow 2.0,
    icon: ti-stats-up,
    description: 'See the impacts of global warming in your area, weather, water.',
    active: # Add true to select section
  }


# Portfolio Page
portfolio-label:
- {
    title : "UI/UX Design",
    type : "design"
  }
- {
    title : "BRANDING",
    type : "branding"
  }
- {
    title : "ILLUSTRATION",
    type : "illustration"
  }


#-------------------------------
# Technologies Slider Section

client-slider-items:
  # Technologies slider
  - logo: "assets/images/tech-logo/tensorflow.png"
    url: "https://www.tensorflow.org"

  - logo: "assets/images/tech-logo/python-logo.png"
    url: "https://www.python.org"

  - logo: "assets/images/tech-logo/kubernetes.png"
    url: "https://www.kubernetes.io"


  - logo: "assets/images/tech-logo/github_logo.png"
    url: "https://www.github.com"



#-------------------------------
# Contact Section

contact-title: wht
contact-email: steve.fruits@email.com
